"""empty message

Revision ID: be1b2f4115d8
Revises: e2c86ad35888
Create Date: 2021-05-06 16:55:39.948765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1b2f4115d8'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_sound', sa.String(length=200), nullable=False),
    sa.Column('bird_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bird_capture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en', sa.String(length=50), nullable=False),
    sa.Column('cnt', sa.String(length=50), nullable=False),
    sa.Column('loc', sa.String(length=200), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('rmk', sa.String(length=500), nullable=False),
    sa.Column('privacy', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('bio', sa.String(length=500), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'bio')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('bird_capture')
    op.drop_table('audio_favorite')
    # ### end Alembic commands ###
